---
title: "Tidy Tuesday "
subtitle: 'Survivor'
author: "Helena"
date: " `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
    highlight: tango
    code_folding: hide
---


# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(tidytuesdayR)
library(survivoR)
library(GGally)
library(xaringanthemer)
library(showtext)
style_mono_accent(
  base_color = "#2a6a6c",               # dark slate green
  inverse_background_color = "#002B36", # dark dark blue
  inverse_header_color = "#31b09e",     # light aqua green
  inverse_text_color = "#FFFFFF",       # white
  title_slide_background_color = "var(--base)",
  text_font_google = google_font("Kelly Slab"),
  header_font_google = google_font("Oleo Script")
)

```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.



# Readme


https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-06-01/readme.md
# Glimpse Data

Take an initial look at the format of the data available.

```{r Glimpse, include=FALSE}

survivoR::castaways %>% 
  map(glimpse)

summary(survivoR::castaways)
summary(survivoR::viewers)

```



# Visualize

Using your processed dataset, create your unique visualization.

```{r Visualize, fig.width= 9}

a<-viewers%>%select(season_name)%>%unique()%>%nrow()


ggplot2::ggplot(data=viewers, aes(x=episode_date, y=rating_18_49))+
   geom_line(color= 'grey45')+
   labs(x="date", y= 'rating', title='Survivor episode ratings' )+
   geom_smooth(method = "loess", n=a)+
  theme_xaringan( text_font = google_font("Ranga"),
    title_font = google_font("Holtwood One SC"))
  
```

# Save Image

Save your image for sharing. Be sure to use the `#TidyTuesday` hashtag in your post on twitter! 

```{r}

# This will save your most recent plot
ggsave(
  filename = "TT:survivor.png",
  device = "png")

```
